FROM python:3.12-slim

# Gradio 설치
RUN pip install --no-cache-dir fastapi uvicorn bs4 trafilatura


# 작업 디렉토리 생성
WORKDIR /app
COPY /volumes/fastapi-server /app/fastapi-server
WORKDIR /app/fastapi-server

RUN 

EXPOSE 9999


# PROD
CMD ["uvicorn", "app:app","--host", "0.0.0.0", "--port", "9999", "--reload"]

# DEV
# CMD ["sleep", "infinity"]

