FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    curl \
    libopenblas-dev \
    libcurl4-openssl-dev \ 
    ninja-build \
    && apt-get clean

WORKDIR /workspace/llama.cpp

# llama.cpp 클론
# RUN git clone https://github.com/ggerganov/llama.cpp.git
# WORKDIR /workspace/llama.cpp

# 빌드
# RUN cmake \
#       -DGGML_CUDA=ON \
#       -DLLAMA_BUILD_SERVER=ON \
#       -DLLAMA_SERVER_JINJA=ON \
#       -DBUILD_SHARED_LIB=OFF \
#       -B build && \
#       cmake --build build --config Release

# 서버 실행
# CMD ["sleep", "infinity"]

CMD ["/workspace/llama.cpp/build/bin/llama-server", \
     "--model", "/models/EXAONE-3.5-7.8B-Instruct-q4_k_m/EXAONE-3.5-7.8B-Instruct-q4_k_m.gguf", \
     "--chat-template", "openai", "--jinja", \
     "--port", "8080", \
     "--host", "0.0.0.0", \
     "--n-gpu-layers", "-1"]