FROM python:3.11-slim

RUN apt update && apt install -y wget
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y ./google-chrome-stable_current_amd64.deb

COPY . /fastapi-server

WORKDIR /fastapi-server
RUN chmod +x ./entrypoint.sh

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

WORKDIR /fastapi-server/app

EXPOSE 9999
CMD ["/bin/sh","/fastapi-server/entrypoint.sh"]
