FROM python:3.11-slim

# Gradio 설치
RUN pip install --upgrade pip && \
    pip install --no-cache-dir fastapi uvicorn bs4 trafilatura fastapi_router_controller httpx tritonclient grpcio-tools packaging


# 작업 디렉토리 생성
WORKDIR /fastapi-server/app

EXPOSE 9999

